#    func_print_head "Copy MongoDB repo"
#    cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#    func_stat_check $?
#
#    func_print_head "Install MongoDB Client"
#    yum install mongodb-org-shell -y &>>$log_file
#    func_stat_check $?
#
#    func_print_head "Load Schema"
#    mongo --host mongodb-dev.rdevopsb72.online </app/schema/${component}.js &>>$log_file
#    func_stat_check $?

- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js






